### ISSUE TITLE
running rewriting-interface issue

### ISSUE THREAD

**Issue by ucaswindlike** [davidbau/rewriting#3]
when running rewriting-interface, it comes out an error: errono13 Permission denied:'/temp/torch_extensions/fused'

**Comment by davidbau** [comment]
This is due to a pytorch bug that shows up on shared systems where /temp/ may also be used by another user.  Somebody else has created that temp directory and you do not have access.

https://github.com/pytorch/pytorch/issues/34238

You can use the env variable `TORCH_EXTENSIONS_DIR` to change the dirname to avoid this (e.g., in your .bashrc)
`export TORCH_EXTENSIONS_DIR="/tmp/${USER}/torch_extensions"`
